config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get :video, controller: :pages
  get :team, controller: :pages

  root 'magazines#index'
  resources :magazines, only: [:index, :show]
  resources :users, only: [:new, :create]
end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/magazine.rb
class Magazine < ActiveRecord::Base
  has_many :sheets
  belongs_to :cover, class_name: 'Sheet'
end

app/models/sheet.rb
class Sheet < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  belongs_to :magazine
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :phone, :firstname, :email, presence: true
  validates :email, :phone, uniqueness: true
  validates :phone, length: { is: 10 }

  def phone=(phone)
    super(phone.tr('^0-9', ''))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/magazines_controller.rb
class MagazinesController < ApplicationController
  def index
    @magazines = Magazine.includes(:cover).order(released_at: :desc).group_by { |magazine| magazine.released_at.year }
  end

  def show
    @magazine = Magazine.find(params[:id])
    @sheets = @magazine.sheets
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  inherit_resources
  actions :new, :create

  private
  def permitted_params
    params.permit(user: [:phone, :email, :firstname, :lastname])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def headline(text = nil)
    text ||= t('.headline')
    content_tag :div, class: 'main-right-title' do
      [ content_tag(:div, '', class: 'main-right-title-pad'),
        content_tag( :h1, text)
      ].join.html_safe
    end.html_safe
  end

  def page_class
    classes = ["#{action_name.parameterize.dasherize}-action"]
    controller_class = "#{controller_name}_controller".classify.constantize
    ancestors = controller_class.ancestors.select {|klass| klass.to_s =~ /Controller/ }
    ancestors.each do |ancestor|
      class_name = ancestor.to_s.underscore.gsub('_', '-')
      return classes.join(' ') if class_name == 'application-controller'
      classes << class_name
    end
  end
end

app/views/layouts/_footer.slim
.main-links
  .main-links-item.main-links-item-shop style=("padding-top: 34px;")
    a href="#" /
    div style=("width:190px; height:128px;")
    .main-links-item-title Интернет-магазин
    ul.g-layout
      li
        a href="#" target="_blank"  Л'Этуаль sélection на letu.ru
      li
        a href="#" target="_blank"  24 часа красоты в интернет-магазине letu.ru
  .main-links-item.main-links-item-ps
    .main-links-item-title Подарочные сертификаты
    ul.g-layout
      li
        a href="#" target="_blank"  Л’Этуаль eCARDS
      li
        a href="/company/ps"  Сертификаты CLASSIC
      li
        a href="/club/gifts/"  Корпоративные сертификаты
  .main-links-item.main-links-item-personal
    .main-links-item-title Личный кабинет
    ul.g-layout
      li
        a href="/company/subscribe/"  SMS/E-MAIL подписка
      li
        a href="/services/unsubscribe.phtml"  Отказаться от e-mail / смс рассылки
  .main-links-item.main-links-item-special
    .main-links-item-title Рекомендуем
    ul.g-layout
      li
        a href="/club/new"  Новинки
      li
        a href="/recommend/tags/Dlya-zhenschin"  Женщинам
      li
        a href="/recommend/tags/Dlya-muzhchin"  Мужчинам
  .main-links-item.main-links-item-events
    .main-links-item-title Акции
    ul.g-layout
      li
        a href="/club/events?news=4597"  Акция "Именинники"
      li
        a href="/club/events?news=4763"  Прекрасные недели весь июль!
  .g-clear
  .main-subscription
    .main-subscription-title.main-links-item-title
      a href="/company/subscribe/" style=("color: white")  Подписка на новости (SMS / E-MAIL)

  .main-footer
    .main-footer-left
      .main-footer-left-copyright © 2006–2016, L'etoile.
      .main-footer-left-social
        a href="#" target="_blank"
          = image_tag 'letmag/icon_vkontakte.png', title: 'В Контакте'
        a href="#" target="_blank"
          = image_tag 'letmag/icon_odnoklassniki.png', title: 'Одноклассники'
        a href="#" target="_blank"
          = image_tag 'letmag/icon_facebook.png', title: 'Facebook'
        a href="#" target="_blank"
          = image_tag 'letmag/icon_lj.png', title: 'LiveJournal'
        a href="#" target="_blank"
          = image_tag 'letmag/icon_twitter.png', title: 'Twitter'
        a href="#" target="_blank"
          = image_tag 'letmag/icon_instagram.png', title: 'Instagram'
    .main-footer-right
      .main-footer-right-rss
        a href="/feedback/"
          = image_tag 'letmag/icon_feedback.png', title: 'Обратная связь'
    .g-clear

app/views/layouts/_header.slim
.main-header.main-header-w-anons
  .main-header-box
    .main-header-logo
      a href="/"
        = image_tag 'letmag/letoile_logo2.gif'
    .main-header-phone
      .header-phone-top
        | Телефон горячей линии
      .header-phone-mid
        | 8 800 200 2345
      .header-phone-bot
        | Звонок по России бесплатный
    .main-header-account
      .header-account-form
        form action="/club/cards/account#account-check-block" method="get" name="quick_account_form"
          span.header-account-form-close
            a href="#"
              = image_tag 'letmag/dialog_close_gray.gif'
          .header-account-form-extra style=("display: none;")
            .header-account-form-extra-title Выберите цвет Вашей карты:
            .header-account-form-extra-left
              div
                input#card1.g-radio name="card_type" type="radio" value="2" /
                label for="card1"  рубиновая
              div
                input#card2.g-radio name="card_type" type="radio" value="3" /
                label for="card2"  сапфировая
              div
                input#card3.g-radio name="card_type" type="radio" value="4" /
                label for="card3"  аметистовая
              div
                input#card4.g-radio name="card_type" type="radio" value="5" /
                label for="card4"  бриллиантовая
            .header-account-form-extra-right
              div
                input#card0_old.g-radio name="card_type" type="radio" value="1_old" /
                label for="card0_old"  зеленая
              div
                input#card1_old.g-radio name="card_type" type="radio" value="2_old" /
                label for="card1_old"  красная
              div
                input#card2_old.g-radio name="card_type" type="radio" value="3_old" /
                label for="card2_old"  синяя
              div
                input#card3_old.g-radio name="card_type" type="radio" value="4_old" /
                label for="card3_old"  серебряная
              div
                input#card4_old.g-radio name="card_type" type="radio" value="5_old" /
                label for="card4_old"  золотая
      .header-account-banner-title-shadow Журнал Л’Этуаль
      .header-account-banner-title
        a href="/company/letmag/"  Журнал Л’Этуаль

app/views/layouts/_left.slim
.main-left.col-xs-12.skip-padding
  .main-left-title= t('.headline')
  ul.main-left-menu.g-layout
    li.left-menu-item
      = link_to t('.team'), team_path, class: 'left-menu-item-link'
    li.left-menu-item
      = link_to t('.for_cooperation'), '#', class: 'left-menu-item-link'
    li.left-menu-item
      = link_to t('.video'), video_path, class: 'left-menu-item-link'
    li.left-menu-item
      = link_to t('.subscription'), new_user_path, class: 'left-menu-item-link'

app/views/layouts/application.slim
doctype html
html
  head
    title Modistka
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body class=page_class
    .fader style=("display: none;")
    .faderIn style=("display: none;")
    .body-box.container
      .main
        = render partial: 'layouts/header'
        .col-xs-12.skip-padding
          .col-xs-3.skip-padding-left
            = render partial: 'layouts/left'
          .main-right.col-xs-9.skip-padding.pull-right
            .main-right-box
              .main-right-box2= yield

        = render partial: 'layouts/footer'

app/views/magazines/_left.slim
.main-left
  .main-left-title= t('.headline')
  ul.main-left-menu.g-layout
    - %w(team for_cooperation video subscription).each do |link|
      li.left-menu-item
        a.left-menu-item-link href='#'= t(".#{link}")

app/views/magazines/index.slim
= headline("Журнал Л'Этуаль")
.news.news-narrow
  - @magazines.each do |year, magazines|
    .news-folder-title= t('year', year: year)
    - magazines.each_with_index do |magazine, index|
      .news-item class=(index % 4 == 0 ? 'news-item-left' : '')
        .news-item-title
          = link_to l(magazine.released_at), magazine_path(magazine), title: l(magazine.released_at)
        .news-item-image
          = link_to magazine_path(magazine), title: l(magazine.released_at) do
            = image_tag(magazine.cover.image.cover.url)
        = link_to 'Читать', magazine_path(magazine), title: l(magazine.released_at), class: 'g-link'
.g-clear

app/views/magazines/show.slim
= headline("Журнал Л'Этуаль: #{l(@magazine.released_at)}")
.news-single.text-content
  .magazine-image
    a href="javascript:;" title=("Следующая страница")
      = image_tag(@sheets.first.image.page.url)
  .magazine
    a.magazine-control-prev.prev href="javascript:;"
    .magazine-scroll
      .magazine-scroll-items
        - index = 0
        - groups = @sheets.each_slice(6).to_a
        - groups.each do |group|
          div
            - group.each do |sheet|
              - index += 1
              = link_to sheet.image.page.url, rel: index, class: 'magazine-item' do
                = image_tag sheet.image.thumb.url
    a.magazine-control-next.next href="javascript:;"
    .g-clear
    .magazine-scroll-navi.navi style=("width: 518px")
      - groups.each_index do |index|
        a href=("##{index}") class=('active' if index == 0)
.g-clear

app/views/pages/team.slim
= headline
.news.news-narrow
  - %w(yana boris ruslan maria artur kirill).each do |person|
    .media
      .col-xs-4
        .media-left
          - path = "pages/team/#{person}.png"
          - if resolve_asset_path(path)
            = image_tag path, class: 'img-responsive'
      .col-xs-8
        .media-body
          .col-xs-12
            h4.media-heading= t(".#{person}.name")
            = t(".#{person}.position")

app/views/pages/video.slim
iframe[ allowfullscreen='' frameborder='0' height='300' mozallowfullscreen=''
        src='https://player.vimeo.com/video/176472163' webkitallowfullscreen='' width='100%' ]
  p
    = link_to t('.headline'), 'https://vimeo.com/176472163'
    = t('.from')
    = link_to t('.channel'), 'https://vimeo.com/arthurnovoslov'

app/views/users/new.slim
= headline
== t('.text')
br
== t('.text')
.block
  = simple_form_for @user, html: { class: 'form-horizontal' }, wrapper: :horizontal_form_5_7 do |f|
    = f.input :phone
    = f.input :email
    = f.input :firstname
    = f.input :lastname
    = f.button :submit, class: 'btn btn-info'